"""Report Generator - Produces structured research reports from all agent outputs."""
from typing import Dict, List, Any
from datetime import datetime
from autoresearch.agents.base_agent import BaseAgent

class ReportGenerator(BaseAgent):
    def __init__(self, db_session=None, llm_client=None):
        super().__init__("ReportGenerator", db_session, llm_client)

    def generate_report(self, discovery, reading, network, gap, hypothesis, verification, topic):
        self.start_timer()
        self.log("Generating final report")

        report = {
            "metadata": {
                "title": f"AutoResearch Report: {topic}",
                "generated_at": datetime.utcnow().isoformat(),
                "system": "AutoResearch v3.0",
                "agents": ["LiteratureDiscovery", "DeepReading", "CitationNetwork",
                          "GapDetection", "HypothesisGeneration", "CriticVerification"]
            },
            "executive_summary": self._executive_summary(discovery, gap, hypothesis, verification),
            "literature_overview": self._literature_overview(discovery, reading),
            "network_analysis": self._network_analysis(network),
            "gap_analysis": self._gap_analysis(gap),
            "hypotheses": self._hypotheses_section(hypothesis, verification),
            "recommendations": self._recommendations(gap, verification)
        }

        duration = self.stop_timer()
        report["metadata"]["duration_seconds"] = round(duration, 2)
        return report

    def generate_markdown(self, report: Dict) -> str:
        md = f"# {report['metadata']['title']}\n\n"
        md += f"**Generated:** {report['metadata']['generated_at'][:10]}  \n"
        md += f"**System:** {report['metadata']['system']}\n\n---\n\n"
        md += report['executive_summary'] + "\n\n---\n\n"

        lo = report['literature_overview']
        md += f"## 1. Literature Overview\n\n**Papers Analyzed:** {lo['papers_analyzed']}  \n"
        md += f"**Year Range:** {lo['year_range']}\n\n### Top Domains\n"
        for d, c in list(lo['top_domains'].items())[:5]:
            md += f"- **{d.replace('_', ' ').title()}**: {c} papers\n"

        md += "\n### Highly Cited Papers\n"
        for p in lo['highly_cited_papers'][:5]:
            md += f"- {p['title']} ({p['citations']} citations)\n"

        na = report['network_analysis']
        md += f"\n---\n\n## 2. Citation Network\n\n"
        md += f"Nodes: {na['network_stats']['num_nodes']} | "
        md += f"Edges: {na['network_stats']['num_edges']} | "
        md += f"Clusters: {na['network_stats']['num_clusters']}\n\n"

        for c in na['research_clusters'][:3]:
            md += f"**Cluster {c['id']}** ({c['size']} papers): {', '.join(c['domains'])}\n"

        ga = report['gap_analysis']
        md += f"\n---\n\n## 3. Research Gaps ({ga['total_gaps']} found)\n\n"
        for i, g in enumerate(ga['top_gaps'][:5], 1):
            md += f"**{i}. [{g['type'].replace('_', ' ').title()}]** (Score: {g['score']})\n"
            md += f"> {g['description']}\n\n"

        h = report['hypotheses']
        md += f"---\n\n## 4. Verified Hypotheses\n\n"
        md += f"Generated: {h['total_generated']} | Verified: {h['total_verified']}\n\n"
        for i, hyp in enumerate(h['top_hypotheses'][:5], 1):
            md += f"**{i}.** {hyp['hypothesis']}\n"
            md += f"- Confidence: {hyp['confidence']*100:.0f}% | Feasibility: {hyp['feasibility'].title()}\n\n"

        md += "---\n\n## 5. Recommendations\n\n"
        for rec in report['recommendations']:
            md += f"**[{rec['priority'].upper()}]** {rec['action']}\n"
            md += f"> {rec['details']}\n\n"

        md += "\n---\n\n*Generated by AutoResearch Multi-Agent System*"
        return md

    def _executive_summary(self, discovery, gaps, hypotheses, verification):
        total_papers = discovery.get("total_found", 0)
        total_gaps = gaps.get("total_gaps", 0)
        total_hyp = hypotheses.get("total_hypotheses", 0)
        verified = verification.get("total_verified", 0)
        top = verification.get("verified_hypotheses", [{}])[0]
        return f"""## Executive Summary
This analysis examined **{total_papers} papers** to identify research opportunities.
**Key Findings:**
- {total_gaps} research gaps identified across multiple categories
- {total_hyp} testable hypotheses generated
- {verified} hypotheses verified against existing literature
**Top Opportunity:** {top.get('hypothesis', 'N/A')[:200]}...
(Confidence: {top.get('confidence', 0)*100:.0f}%)"""

    def _literature_overview(self, discovery, reading):
        papers = discovery.get("papers", [])
        summary = reading.get("summary", {})
        years = [p.get("published_year") for p in papers if p.get("published_year")]
        year_range = f"{min(years)}-{max(years)}" if years else "N/A"
        return {
            "papers_analyzed": len(papers),
            "year_range": year_range,
            "top_domains": summary.get("domains", {}),
            "top_methods": summary.get("methodologies", {}),
            "highly_cited_papers": [
                {"title": p.get("title", "")[:80], "citations": p.get("citation_count", 0) or 0}
                for p in sorted(papers, key=lambda x: x.get("citation_count", 0) or 0, reverse=True)[:5]
            ]
        }

    def _network_analysis(self, network):
        return {
            "network_stats": network.get("network_stats", {}),
            "research_clusters": network.get("clusters", [])[:5],
            "bridge_papers": network.get("bridge_papers", [])[:5],
            "influential_papers": network.get("influential_papers", [])[:5]
        }

    def _gap_analysis(self, gap_result):
        return {
            "total_gaps": gap_result.get("total_gaps", 0),
            "gap_categories": gap_result.get("gap_categories", {}),
            "top_gaps": gap_result.get("gaps", [])[:8]
        }

    def _hypotheses_section(self, hypothesis_result, verification_result):
        return {
            "total_generated": hypothesis_result.get("total_hypotheses", 0),
            "total_verified": verification_result.get("total_verified", 0),
            "verification_rate": verification_result.get("verification_stats", {}).get("verification_rate", 0),
            "top_hypotheses": [
                {
                    "hypothesis": v.get("hypothesis", ""),
                    "confidence": v.get("confidence", 0),
                    "feasibility": v.get("feasibility", "unknown")
                }
                for v in verification_result.get("verified_hypotheses", [])[:5]
            ]
        }

    def _recommendations(self, gap_result, verification_result):
        recs = []
        verified = verification_result.get("verified_hypotheses", [])
        if verified:
            recs.append({
                "priority": "high",
                "action": "Pursue top-verified hypothesis",
                "details": verified[0].get("hypothesis", ""),
                "rationale": f"Highest confidence ({verified[0].get('confidence', 0)*100:.0f}%)"
            })
        gaps = gap_result.get("gaps", [])
        method_gaps = [g for g in gaps if g.get("type") == "methodological"]
        if method_gaps:
            recs.append({
                "priority": "medium",
                "action": "Explore methodological transfer",
                "details": method_gaps[0].get("description", ""),
                "rationale": "High-feasibility opportunity"
            })
        recs.append({
            "priority": "low",
            "action": "Expand literature search",
            "details": "Search additional databases (IEEE, ACM, DBLP)",
            "rationale": "Broader coverage improves accuracy"
        })
        return recs

    def execute(self, *args, **kwargs):
        return self.generate_report(*args, **kwargs)
